"""
Agent models - synthetic decision-makers.
This is the Behavioral Model (Layer 3).
"""

from pydantic import BaseModel, Field
from typing import Dict, List, Optional


class Persona(BaseModel):
    """Rich persona generated by LLM for deep-dive interactions"""
    name: str
    role: str
    company_name: str
    company_description: str
    background: str
    current_challenges: List[str]
    buying_history: List[str]
    communication_style: str


class Belief(BaseModel):
    """Agent's belief about a product"""
    product_id: str
    perceived_quality: Dict[str, float]  # feature -> perceived score
    trust_level: float = Field(ge=0, le=1)
    source: str  # "advertising", "peer", "demo", "trial"
    confidence: float = Field(ge=0, le=1)


class DecisionEvent(BaseModel):
    """A logged event in the agent's decision journey"""
    day: int
    event_type: str  # "awareness", "stage_change", "touchpoint", "decision"
    description: str
    inputs: Dict
    output: str
    reasoning: Optional[str] = None  # LLM-generated on demand


class Agent(BaseModel):
    """
    A synthetic decision-maker.
    Core behavioral model that makes decisions during simulation.
    """
    id: str
    segment_id: str

    # Identity (optional, for deep-dive)
    persona: Optional[Persona] = None

    # Firmographics
    company_size: int = 100
    budget: int = 50000

    # Behavioral parameters (sampled from segment profile)
    risk_tolerance: float = Field(ge=0, le=1)
    price_sensitivity: float = Field(ge=0, le=1)
    feature_priorities: Dict[str, float]
    decision_speed: float = Field(ge=0, le=1)
    influencer_susceptibility: float = Field(ge=0, le=1)

    # Current state
    stage: str = "Unaware"
    awareness: Dict[str, float] = {}  # product_id -> awareness level
    consideration_set: List[str] = []
    beliefs: Dict[str, Belief] = {}

    # Social graph
    connections: List[str] = []  # other agent IDs
    influence_score: float = 0.5

    # Decision trace (for explainability)
    decision_log: List[DecisionEvent] = []

    # Final decision
    final_decision: Optional[str] = None  # product_id or None
    decision_day: Optional[int] = None

    def add_event(
        self,
        day: int,
        event_type: str,
        description: str,
        inputs: Dict,
        output: str
    ):
        """Add event to decision log"""
        self.decision_log.append(DecisionEvent(
            day=day,
            event_type=event_type,
            description=description,
            inputs=inputs,
            output=output
        ))

    class Config:
        # Allow mutation for simulation updates
        validate_assignment = True
