"""
Export Engine
Generate markdown and PDF exports of decision analyses
"""

import os
from typing import Dict, Any, List, Optional
from datetime import datetime
from io import BytesIO

from backend.models.decision import Decision
from backend.models.scenario_branch import ScenarioTree, ScenarioSummary
from backend.models.confidence import ConfidenceDecomposition
from backend.models.journal import DecisionJournal, JournalExport


class ExportEngine:
    """
    Engine for exporting decision analyses to various formats.
    Supports markdown and PDF.
    """

    def __init__(self):
        pass

    def export_decision_to_markdown(
        self,
        decision: Decision,
        scenario_summary: Optional[ScenarioSummary] = None,
        confidence: Optional[ConfidenceDecomposition] = None,
        journal: Optional[DecisionJournal] = None,
        competitor_analysis: Optional[Dict] = None,
    ) -> str:
        """
        Export a complete decision analysis to markdown format.
        """
        lines = []

        # Header
        lines.append(f"# {decision.title}")
        lines.append("")
        lines.append(f"*Generated by Populous - {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append("")
        if scenario_summary:
            lines.append(f"**{scenario_summary.headline}**")
            lines.append("")

        lines.append(f"**Context:** {decision.context or 'No context provided'}")
        lines.append("")

        # Options
        lines.append("## Decision Options")
        lines.append("")
        for i, option in enumerate(decision.options, 1):
            lines.append(f"### Option {i}: {option.name}")
            lines.append("")
            lines.append(option.description)
            lines.append("")

        # Scenario Analysis
        if scenario_summary:
            lines.append("## Scenario Analysis")
            lines.append("")
            lines.append("### Outcome Probabilities")
            lines.append("")
            lines.append("| Outcome | Probability |")
            lines.append("|---------|-------------|")
            for outcome in scenario_summary.outcomes:
                lines.append(f"| {outcome.get('outcome', 'Unknown')} | {int(outcome.get('probability', 0) * 100)}% |")
            lines.append("")

            if scenario_summary.best_case:
                lines.append("### Best Case Scenario")
                lines.append("")
                lines.append(f"**Probability:** {int(scenario_summary.best_case.get('probability', 0) * 100)}%")
                lines.append("")
                lines.append(scenario_summary.best_case.get('narrative', ''))
                lines.append("")

            if scenario_summary.worst_case:
                lines.append("### Worst Case Scenario")
                lines.append("")
                lines.append(f"**Probability:** {int(scenario_summary.worst_case.get('probability', 0) * 100)}%")
                lines.append("")
                lines.append(scenario_summary.worst_case.get('narrative', ''))
                lines.append("")

            if scenario_summary.key_risks:
                lines.append("### Key Risks")
                lines.append("")
                for risk in scenario_summary.key_risks:
                    lines.append(f"- {risk}")
                lines.append("")

            if scenario_summary.key_opportunities:
                lines.append("### Key Opportunities")
                lines.append("")
                for opp in scenario_summary.key_opportunities:
                    lines.append(f"- {opp}")
                lines.append("")

        # Competitor Analysis
        if competitor_analysis:
            lines.append("## Competitive Analysis")
            lines.append("")

            if competitor_analysis.get("nash_equilibrium"):
                nash = competitor_analysis["nash_equilibrium"]
                lines.append("### Nash Equilibrium")
                lines.append("")
                lines.append(f"**Your Strategy:** {nash.get('your_strategy', 'Unknown')}")
                lines.append(f"**Their Strategy:** {nash.get('their_strategy', 'Unknown')}")
                lines.append(f"**Interpretation:** {nash.get('interpretation', '')}")
                lines.append("")

            if competitor_analysis.get("competitor_responses"):
                lines.append("### Expected Competitor Responses")
                lines.append("")
                for comp_id, response in competitor_analysis["competitor_responses"].items():
                    lines.append(f"**{response.get('name', comp_id)}**")
                    lines.append(f"- Most likely: {response.get('most_likely_response', 'Unknown')}")
                    lines.append(f"- Probability: {int(response.get('probability', 0) * 100)}%")
                    lines.append("")

            if competitor_analysis.get("risk_factors"):
                lines.append("### Risk Factors")
                lines.append("")
                for risk in competitor_analysis["risk_factors"]:
                    lines.append(f"- {risk}")
                lines.append("")

        # Confidence Analysis
        if confidence:
            lines.append("## Confidence Analysis")
            lines.append("")
            lines.append(f"**Overall Confidence:** {int(confidence.overall_confidence * 100)}%")
            lines.append(f"**Confidence Level:** {confidence.confidence_level.value}")
            lines.append("")

            lines.append("### Uncertainty Breakdown")
            lines.append("")
            lines.append("| Source | Contribution | Reducible |")
            lines.append("|--------|--------------|-----------|")
            for comp in confidence.components:
                reducible = "Yes" if comp.reducible else "No"
                lines.append(f"| {comp.name} | {int(comp.contribution * 100)}% | {reducible} |")
            lines.append("")

            if confidence.confidence_improvement_actions:
                lines.append("### To Increase Confidence")
                lines.append("")
                for action in confidence.confidence_improvement_actions:
                    lines.append(f"- {action}")
                lines.append("")

        # Recommendations
        lines.append("## Recommendations")
        lines.append("")
        if scenario_summary and scenario_summary.recommended_actions:
            for action in scenario_summary.recommended_actions:
                lines.append(f"1. {action}")
            lines.append("")
        else:
            lines.append("No specific recommendations generated.")
            lines.append("")

        # Journal Summary
        if journal:
            lines.append("## Decision Journal")
            lines.append("")
            lines.append(f"**Total Entries:** {len(journal.entries)}")
            lines.append(f"**Predictions Made:** {journal.total_predictions}")
            if journal.predictions_validated > 0:
                lines.append(f"**Predictions Validated:** {journal.predictions_validated}")
                lines.append(f"**Overall Accuracy:** {int(journal.overall_accuracy * 100)}%")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*There's a future where you win; we engineer that for you.*")
        lines.append("")
        lines.append(f"Report generated by **Populous** | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        return "\n".join(lines)

    def export_decision_to_pdf(
        self,
        decision: Decision,
        scenario_summary: Optional[ScenarioSummary] = None,
        confidence: Optional[ConfidenceDecomposition] = None,
        journal: Optional[DecisionJournal] = None,
        competitor_analysis: Optional[Dict] = None,
    ) -> bytes:
        """
        Export a complete decision analysis to PDF format.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib import colors as rl_colors

            buffer = BytesIO()
            doc = SimpleDocTemplate(
                buffer,
                pagesize=letter,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=72
            )

            styles = getSampleStyleSheet()
            story = []

            # Title
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                spaceAfter=12,
            )
            story.append(Paragraph(decision.title, title_style))
            story.append(Spacer(1, 12))

            # Subtitle
            subtitle_style = ParagraphStyle(
                'Subtitle',
                parent=styles['Normal'],
                fontSize=10,
                textColor=rl_colors.grey,
            )
            story.append(Paragraph(
                f"Generated by Populous - {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                subtitle_style
            ))
            story.append(Spacer(1, 24))

            # Executive Summary
            story.append(Paragraph("Executive Summary", styles['Heading2']))
            story.append(Spacer(1, 12))

            if scenario_summary:
                highlight_style = ParagraphStyle(
                    'Highlight',
                    parent=styles['Normal'],
                    fontSize=14,
                    textColor=rl_colors.darkblue,
                    spaceAfter=12,
                )
                story.append(Paragraph(scenario_summary.headline, highlight_style))

            story.append(Paragraph(
                f"<b>Context:</b> {decision.context or 'No context provided'}",
                styles['Normal']
            ))
            story.append(Spacer(1, 24))

            # Options
            story.append(Paragraph("Decision Options", styles['Heading2']))
            story.append(Spacer(1, 12))

            for i, option in enumerate(decision.options, 1):
                story.append(Paragraph(f"Option {i}: {option.name}", styles['Heading3']))
                story.append(Paragraph(option.description, styles['Normal']))
                story.append(Spacer(1, 12))

            # Scenario Analysis
            if scenario_summary:
                story.append(Paragraph("Scenario Analysis", styles['Heading2']))
                story.append(Spacer(1, 12))

                # Outcome probabilities table
                if scenario_summary.outcomes:
                    table_data = [['Outcome', 'Probability']]
                    for outcome in scenario_summary.outcomes:
                        table_data.append([
                            outcome.get('outcome', 'Unknown'),
                            f"{int(outcome.get('probability', 0) * 100)}%"
                        ])

                    table = Table(table_data, colWidths=[3*inch, 1.5*inch])
                    table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), rl_colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), rl_colors.black),
                        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                        ('GRID', (0, 0), (-1, -1), 1, rl_colors.black),
                    ]))
                    story.append(table)
                    story.append(Spacer(1, 12))

                # Key risks
                if scenario_summary.key_risks:
                    story.append(Paragraph("Key Risks", styles['Heading3']))
                    for risk in scenario_summary.key_risks:
                        story.append(Paragraph(f"• {risk}", styles['Normal']))
                    story.append(Spacer(1, 12))

            # Confidence Analysis
            if confidence:
                story.append(Paragraph("Confidence Analysis", styles['Heading2']))
                story.append(Spacer(1, 12))

                story.append(Paragraph(
                    f"<b>Overall Confidence:</b> {int(confidence.overall_confidence * 100)}% ({confidence.confidence_level.value})",
                    styles['Normal']
                ))
                story.append(Spacer(1, 12))

                # Uncertainty table
                table_data = [['Source', 'Contribution', 'Reducible']]
                for comp in confidence.components[:5]:
                    table_data.append([
                        comp.name,
                        f"{int(comp.contribution * 100)}%",
                        "Yes" if comp.reducible else "No"
                    ])

                table = Table(table_data, colWidths=[2.5*inch, 1.5*inch, 1*inch])
                table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), rl_colors.lightgrey),
                    ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, rl_colors.black),
                ]))
                story.append(table)
                story.append(Spacer(1, 24))

            # Recommendations
            story.append(Paragraph("Recommendations", styles['Heading2']))
            story.append(Spacer(1, 12))

            if scenario_summary and scenario_summary.recommended_actions:
                for i, action in enumerate(scenario_summary.recommended_actions, 1):
                    story.append(Paragraph(f"{i}. {action}", styles['Normal']))
            else:
                story.append(Paragraph("No specific recommendations generated.", styles['Normal']))
            story.append(Spacer(1, 24))

            # Footer
            footer_style = ParagraphStyle(
                'Footer',
                parent=styles['Normal'],
                fontSize=10,
                textColor=rl_colors.grey,
                alignment=1,  # Center
            )
            story.append(Paragraph(
                "There's a future where you win; we engineer that for you.",
                footer_style
            ))
            story.append(Spacer(1, 6))
            story.append(Paragraph(
                f"Report generated by Populous | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                footer_style
            ))

            doc.build(story)
            return buffer.getvalue()

        except ImportError:
            # Fallback if reportlab is not installed
            markdown = self.export_decision_to_markdown(
                decision, scenario_summary, confidence, journal, competitor_analysis
            )
            return markdown.encode('utf-8')

    def export_journal_to_markdown(
        self,
        export: JournalExport,
    ) -> str:
        """
        Export a decision journal to markdown.
        """
        lines = []

        # Header
        lines.append(f"# Decision Journal: {export.decision_title}")
        lines.append("")
        lines.append(f"*Decision Date: {export.decision_date.strftime('%Y-%m-%d')}*")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(export.decision_summary)
        lines.append("")

        # Timeline
        lines.append("## Timeline")
        lines.append("")
        for event in export.timeline:
            lines.append(f"**{event.get('timestamp', '')}** - {event.get('title', '')}")
            if event.get('description'):
                lines.append(f"  - {event['description']}")
            lines.append("")

        # Predictions vs Outcomes
        lines.append("## Predictions vs Outcomes")
        lines.append("")
        lines.append("| Type | Predicted | Actual | Accuracy |")
        lines.append("|------|-----------|--------|----------|")
        for po in export.prediction_outcomes:
            lines.append(
                f"| {po.get('type', '')} | {po.get('predicted', '')} | "
                f"{po.get('actual', '-')} | {po.get('accuracy', 'pending')} |"
            )
        lines.append("")

        # Lessons Learned
        if export.lessons_learned:
            lines.append("## Lessons Learned")
            lines.append("")
            for lesson in export.lessons_learned:
                lines.append(f"- {lesson}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append(f"*Exported: {export.export_date.strftime('%Y-%m-%d %H:%M:%S')}*")

        return "\n".join(lines)

    def export_competitive_analysis_markdown(
        self,
        company_name: str,
        competitor_analysis: Dict[str, Any],
        game_simulation: Optional[List[Dict]] = None,
    ) -> str:
        """
        Export competitive analysis to markdown.
        """
        lines = []

        # Header
        lines.append(f"# Competitive Analysis: {company_name}")
        lines.append("")
        lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Your Move
        lines.append("## Your Strategic Move")
        lines.append("")
        move = competitor_analysis.get("your_move", {})
        lines.append(f"**Type:** {move.get('type', 'Unknown')}")
        if move.get('percent'):
            lines.append(f"**Magnitude:** {move.get('percent')}%")
        lines.append("")

        # Competitor Responses
        lines.append("## Expected Competitor Responses")
        lines.append("")
        for comp_id, response in competitor_analysis.get("competitor_responses", {}).items():
            lines.append(f"### {response.get('name', comp_id)}")
            lines.append("")
            lines.append(f"**Strategy Type:** {response.get('strategy_type', 'Unknown')}")
            lines.append(f"**Most Likely Response:** {response.get('most_likely_response', 'Unknown')}")
            lines.append(f"**Probability:** {int(response.get('probability', 0) * 100)}%")
            if response.get('response_delay_days'):
                lines.append(f"**Expected Delay:** {response['response_delay_days']} days")
            lines.append("")

        # Scenario Probabilities
        lines.append("## Scenario Probabilities")
        lines.append("")
        lines.append("| Scenario | Probability |")
        lines.append("|----------|-------------|")
        for scenario, prob in competitor_analysis.get("scenario_probabilities", {}).items():
            lines.append(f"| {scenario.replace('_', ' ').title()} | {int(prob * 100)}% |")
        lines.append("")

        # Nash Equilibrium
        if competitor_analysis.get("nash_equilibrium"):
            lines.append("## Game-Theoretic Analysis")
            lines.append("")
            nash = competitor_analysis["nash_equilibrium"]
            lines.append(f"**Equilibrium Type:** {nash.get('type', 'Unknown')}")
            lines.append(f"**Your Optimal Strategy:** {nash.get('your_strategy', 'Unknown')}")
            lines.append(f"**Their Optimal Strategy:** {nash.get('their_strategy', 'Unknown')}")
            lines.append("")
            lines.append(f"**Interpretation:** {nash.get('interpretation', '')}")
            lines.append("")

        # Risk Factors
        if competitor_analysis.get("risk_factors"):
            lines.append("## Risk Factors")
            lines.append("")
            for risk in competitor_analysis["risk_factors"]:
                lines.append(f"- ⚠️ {risk}")
            lines.append("")

        # Recommended Strategies
        if competitor_analysis.get("recommended_strategies"):
            lines.append("## Recommended Counter-Strategies")
            lines.append("")
            for i, strategy in enumerate(competitor_analysis["recommended_strategies"], 1):
                lines.append(f"{i}. {strategy}")
            lines.append("")

        # Game Simulation
        if game_simulation:
            lines.append("## Multi-Round Simulation")
            lines.append("")
            for round_data in game_simulation:
                lines.append(f"### Round {round_data.get('round', '?')}")
                lines.append("")
                lines.append(f"**Your Move:** {round_data.get('your_move', {}).get('type', 'Unknown')}")
                lines.append("")
                for comp_name, resp in round_data.get("competitor_responses", {}).items():
                    if resp:
                        lines.append(f"**{comp_name}:** {resp.get('description', 'No response')}")
                lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*There's a future where you win; we engineer that for you.*")

        return "\n".join(lines)
